// Generated from the client's project photographs. Each entry is a graded,
// cropped WebP pair: `src` for gallery/lightbox, `card` for grid thumbnails.
export type WorkImage = { src: string; card: string };

export const WORK_IMAGES: Record<string, WorkImage[]> = {
  "gates": [
    { src: "/work/gates/gates-01.webp", card: "/work/gates/gates-01-card.webp" },
    { src: "/work/gates/gates-02.webp", card: "/work/gates/gates-02-card.webp" },
    { src: "/work/gates/gates-03.webp", card: "/work/gates/gates-03-card.webp" },
    { src: "/work/gates/gates-04.webp", card: "/work/gates/gates-04-card.webp" },
    { src: "/work/gates/gates-05.webp", card: "/work/gates/gates-05-card.webp" },
    { src: "/work/gates/gates-06.webp", card: "/work/gates/gates-06-card.webp" },
    { src: "/work/gates/gates-07.webp", card: "/work/gates/gates-07-card.webp" },
    { src: "/work/gates/gates-08.webp", card: "/work/gates/gates-08-card.webp" },
    { src: "/work/gates/gates-09.webp", card: "/work/gates/gates-09-card.webp" },
    { src: "/work/gates/gates-10.webp", card: "/work/gates/gates-10-card.webp" },
    { src: "/work/gates/gates-11.webp", card: "/work/gates/gates-11-card.webp" },
  ],
  "aluminium-doors-windows": [
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-01.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-01-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-02.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-02-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-03.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-03-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-04.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-04-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-05.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-05-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-06.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-06-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-07.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-07-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-08.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-08-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-09.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-09-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-10.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-10-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-11.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-11-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-12.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-12-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-13.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-13-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-14.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-14-card.webp" },
    { src: "/work/aluminium-doors-windows/aluminium-doors-windows-15.webp", card: "/work/aluminium-doors-windows/aluminium-doors-windows-15-card.webp" },
  ],
  "steel-fabrication": [
    { src: "/work/steel-fabrication/steel-fabrication-01.webp", card: "/work/steel-fabrication/steel-fabrication-01-card.webp" },
    { src: "/work/steel-fabrication/steel-fabrication-02.webp", card: "/work/steel-fabrication/steel-fabrication-02-card.webp" },
    { src: "/work/steel-fabrication/steel-fabrication-03.webp", card: "/work/steel-fabrication/steel-fabrication-03-card.webp" },
    { src: "/work/steel-fabrication/steel-fabrication-04.webp", card: "/work/steel-fabrication/steel-fabrication-04-card.webp" },
    { src: "/work/steel-fabrication/steel-fabrication-05.webp", card: "/work/steel-fabrication/steel-fabrication-05-card.webp" },
    { src: "/work/steel-fabrication/steel-fabrication-06.webp", card: "/work/steel-fabrication/steel-fabrication-06-card.webp" },
    { src: "/work/steel-fabrication/steel-fabrication-07.webp", card: "/work/steel-fabrication/steel-fabrication-07-card.webp" },
    { src: "/work/steel-fabrication/steel-fabrication-08.webp", card: "/work/steel-fabrication/steel-fabrication-08-card.webp" },
    { src: "/work/steel-fabrication/steel-fabrication-09.webp", card: "/work/steel-fabrication/steel-fabrication-09-card.webp" },
    { src: "/work/steel-fabrication/steel-fabrication-10.webp", card: "/work/steel-fabrication/steel-fabrication-10-card.webp" },
  ],
  "stainless-steel": [
    { src: "/work/stainless-steel/stainless-steel-01.webp", card: "/work/stainless-steel/stainless-steel-01-card.webp" },
    { src: "/work/stainless-steel/stainless-steel-02.webp", card: "/work/stainless-steel/stainless-steel-02-card.webp" },
    { src: "/work/stainless-steel/stainless-steel-03.webp", card: "/work/stainless-steel/stainless-steel-03-card.webp" },
    { src: "/work/stainless-steel/stainless-steel-04.webp", card: "/work/stainless-steel/stainless-steel-04-card.webp" },
    { src: "/work/stainless-steel/stainless-steel-05.webp", card: "/work/stainless-steel/stainless-steel-05-card.webp" },
    { src: "/work/stainless-steel/stainless-steel-06.webp", card: "/work/stainless-steel/stainless-steel-06-card.webp" },
    { src: "/work/stainless-steel/stainless-steel-07.webp", card: "/work/stainless-steel/stainless-steel-07-card.webp" },
    { src: "/work/stainless-steel/stainless-steel-08.webp", card: "/work/stainless-steel/stainless-steel-08-card.webp" },
    { src: "/work/stainless-steel/stainless-steel-09.webp", card: "/work/stainless-steel/stainless-steel-09-card.webp" },
    { src: "/work/stainless-steel/stainless-steel-10.webp", card: "/work/stainless-steel/stainless-steel-10-card.webp" },
    { src: "/work/stainless-steel/stainless-steel-11.webp", card: "/work/stainless-steel/stainless-steel-11-card.webp" },
  ],
  "gypsum-aluminium-partitions": [
    { src: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-01.webp", card: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-01-card.webp" },
    { src: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-02.webp", card: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-02-card.webp" },
    { src: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-03.webp", card: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-03-card.webp" },
    { src: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-04.webp", card: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-04-card.webp" },
    { src: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-05.webp", card: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-05-card.webp" },
    { src: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-06.webp", card: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-06-card.webp" },
    { src: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-07.webp", card: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-07-card.webp" },
    { src: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-08.webp", card: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-08-card.webp" },
    { src: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-09.webp", card: "/work/gypsum-aluminium-partitions/gypsum-aluminium-partitions-09-card.webp" },
  ],
  "cnc-plate-design": [
    { src: "/work/cnc-plate-design/cnc-plate-design-01.webp", card: "/work/cnc-plate-design/cnc-plate-design-01-card.webp" },
    { src: "/work/cnc-plate-design/cnc-plate-design-02.webp", card: "/work/cnc-plate-design/cnc-plate-design-02-card.webp" },
    { src: "/work/cnc-plate-design/cnc-plate-design-03.webp", card: "/work/cnc-plate-design/cnc-plate-design-03-card.webp" },
    { src: "/work/cnc-plate-design/cnc-plate-design-04.webp", card: "/work/cnc-plate-design/cnc-plate-design-04-card.webp" },
    { src: "/work/cnc-plate-design/cnc-plate-design-05.webp", card: "/work/cnc-plate-design/cnc-plate-design-05-card.webp" },
    { src: "/work/cnc-plate-design/cnc-plate-design-06.webp", card: "/work/cnc-plate-design/cnc-plate-design-06-card.webp" },
    { src: "/work/cnc-plate-design/cnc-plate-design-07.webp", card: "/work/cnc-plate-design/cnc-plate-design-07-card.webp" },
    { src: "/work/cnc-plate-design/cnc-plate-design-08.webp", card: "/work/cnc-plate-design/cnc-plate-design-08-card.webp" },
    { src: "/work/cnc-plate-design/cnc-plate-design-09.webp", card: "/work/cnc-plate-design/cnc-plate-design-09-card.webp" },
  ],
  "metal-beds": [
    { src: "/work/metal-beds/metal-beds-01.webp", card: "/work/metal-beds/metal-beds-01-card.webp" },
    { src: "/work/metal-beds/metal-beds-02.webp", card: "/work/metal-beds/metal-beds-02-card.webp" },
    { src: "/work/metal-beds/metal-beds-03.webp", card: "/work/metal-beds/metal-beds-03-card.webp" },
    { src: "/work/metal-beds/metal-beds-04.webp", card: "/work/metal-beds/metal-beds-04-card.webp" },
    { src: "/work/metal-beds/metal-beds-05.webp", card: "/work/metal-beds/metal-beds-05-card.webp" },
    { src: "/work/metal-beds/metal-beds-06.webp", card: "/work/metal-beds/metal-beds-06-card.webp" },
    { src: "/work/metal-beds/metal-beds-07.webp", card: "/work/metal-beds/metal-beds-07-card.webp" },
  ],
  "shower-screens-glass": [
    { src: "/work/shower-screens-glass/shower-screens-glass-01.webp", card: "/work/shower-screens-glass/shower-screens-glass-01-card.webp" },
    { src: "/work/shower-screens-glass/shower-screens-glass-02.webp", card: "/work/shower-screens-glass/shower-screens-glass-02-card.webp" },
    { src: "/work/shower-screens-glass/shower-screens-glass-03.webp", card: "/work/shower-screens-glass/shower-screens-glass-03-card.webp" },
    { src: "/work/shower-screens-glass/shower-screens-glass-04.webp", card: "/work/shower-screens-glass/shower-screens-glass-04-card.webp" },
    { src: "/work/shower-screens-glass/shower-screens-glass-05.webp", card: "/work/shower-screens-glass/shower-screens-glass-05-card.webp" },
  ],
  "gypsum-ceiling": [
    { src: "/work/gypsum-ceiling/gypsum-ceiling-01.webp", card: "/work/gypsum-ceiling/gypsum-ceiling-01-card.webp" },
    { src: "/work/gypsum-ceiling/gypsum-ceiling-02.webp", card: "/work/gypsum-ceiling/gypsum-ceiling-02-card.webp" },
    { src: "/work/gypsum-ceiling/gypsum-ceiling-03.webp", card: "/work/gypsum-ceiling/gypsum-ceiling-03-card.webp" },
    { src: "/work/gypsum-ceiling/gypsum-ceiling-04.webp", card: "/work/gypsum-ceiling/gypsum-ceiling-04-card.webp" },
    { src: "/work/gypsum-ceiling/gypsum-ceiling-05.webp", card: "/work/gypsum-ceiling/gypsum-ceiling-05-card.webp" },
    { src: "/work/gypsum-ceiling/gypsum-ceiling-06.webp", card: "/work/gypsum-ceiling/gypsum-ceiling-06-card.webp" },
    { src: "/work/gypsum-ceiling/gypsum-ceiling-07.webp", card: "/work/gypsum-ceiling/gypsum-ceiling-07-card.webp" },
  ],
  "roller-shutters": [
    { src: "/work/roller-shutters/roller-shutters-01.webp", card: "/work/roller-shutters/roller-shutters-01-card.webp" },
    { src: "/work/roller-shutters/roller-shutters-02.webp", card: "/work/roller-shutters/roller-shutters-02-card.webp" },
    { src: "/work/roller-shutters/roller-shutters-03.webp", card: "/work/roller-shutters/roller-shutters-03-card.webp" },
    { src: "/work/roller-shutters/roller-shutters-04.webp", card: "/work/roller-shutters/roller-shutters-04-card.webp" },
    { src: "/work/roller-shutters/roller-shutters-05.webp", card: "/work/roller-shutters/roller-shutters-05-card.webp" },
    { src: "/work/roller-shutters/roller-shutters-06.webp", card: "/work/roller-shutters/roller-shutters-06-card.webp" },
  ],
  "fencing-boundary-walls": [
    { src: "/work/fencing-boundary-walls/fencing-boundary-walls-01.webp", card: "/work/fencing-boundary-walls/fencing-boundary-walls-01-card.webp" },
    { src: "/work/fencing-boundary-walls/fencing-boundary-walls-02.webp", card: "/work/fencing-boundary-walls/fencing-boundary-walls-02-card.webp" },
    { src: "/work/fencing-boundary-walls/fencing-boundary-walls-03.webp", card: "/work/fencing-boundary-walls/fencing-boundary-walls-03-card.webp" },
    { src: "/work/fencing-boundary-walls/fencing-boundary-walls-04.webp", card: "/work/fencing-boundary-walls/fencing-boundary-walls-04-card.webp" },
    { src: "/work/fencing-boundary-walls/fencing-boundary-walls-05.webp", card: "/work/fencing-boundary-walls/fencing-boundary-walls-05-card.webp" },
    { src: "/work/fencing-boundary-walls/fencing-boundary-walls-06.webp", card: "/work/fencing-boundary-walls/fencing-boundary-walls-06-card.webp" },
  ],
  "burglar-proofing": [
    { src: "/work/burglar-proofing/burglar-proofing-01.webp", card: "/work/burglar-proofing/burglar-proofing-01-card.webp" },
    { src: "/work/burglar-proofing/burglar-proofing-02.webp", card: "/work/burglar-proofing/burglar-proofing-02-card.webp" },
    { src: "/work/burglar-proofing/burglar-proofing-03.webp", card: "/work/burglar-proofing/burglar-proofing-03-card.webp" },
    { src: "/work/burglar-proofing/burglar-proofing-04.webp", card: "/work/burglar-proofing/burglar-proofing-04-card.webp" },
    { src: "/work/burglar-proofing/burglar-proofing-05.webp", card: "/work/burglar-proofing/burglar-proofing-05-card.webp" },
    { src: "/work/burglar-proofing/burglar-proofing-06.webp", card: "/work/burglar-proofing/burglar-proofing-06-card.webp" },
  ],
  "steel-shelving": [
    { src: "/work/steel-shelving/steel-shelving-01.webp", card: "/work/steel-shelving/steel-shelving-01-card.webp" },
    { src: "/work/steel-shelving/steel-shelving-02.webp", card: "/work/steel-shelving/steel-shelving-02-card.webp" },
    { src: "/work/steel-shelving/steel-shelving-03.webp", card: "/work/steel-shelving/steel-shelving-03-card.webp" },
    { src: "/work/steel-shelving/steel-shelving-04.webp", card: "/work/steel-shelving/steel-shelving-04-card.webp" },
  ],
  "pergola-shades": [
    { src: "/work/pergola-shades/pergola-shades-01.webp", card: "/work/pergola-shades/pergola-shades-01-card.webp" },
    { src: "/work/pergola-shades/pergola-shades-02.webp", card: "/work/pergola-shades/pergola-shades-02-card.webp" },
    { src: "/work/pergola-shades/pergola-shades-03.webp", card: "/work/pergola-shades/pergola-shades-03-card.webp" },
    { src: "/work/pergola-shades/pergola-shades-04.webp", card: "/work/pergola-shades/pergola-shades-04-card.webp" },
  ],
  "carport-shades": [
    { src: "/work/carport-shades/carport-shades-01.webp", card: "/work/carport-shades/carport-shades-01-card.webp" },
    { src: "/work/carport-shades/carport-shades-02.webp", card: "/work/carport-shades/carport-shades-02-card.webp" },
    { src: "/work/carport-shades/carport-shades-03.webp", card: "/work/carport-shades/carport-shades-03-card.webp" },
  ],
  "balcony-grills-glass-works": [
    { src: "/work/balcony-grills-glass-works/balcony-grills-glass-works-01.webp", card: "/work/balcony-grills-glass-works/balcony-grills-glass-works-01-card.webp" },
    { src: "/work/balcony-grills-glass-works/balcony-grills-glass-works-02.webp", card: "/work/balcony-grills-glass-works/balcony-grills-glass-works-02-card.webp" },
    { src: "/work/balcony-grills-glass-works/balcony-grills-glass-works-03.webp", card: "/work/balcony-grills-glass-works/balcony-grills-glass-works-03-card.webp" },
    { src: "/work/balcony-grills-glass-works/balcony-grills-glass-works-04.webp", card: "/work/balcony-grills-glass-works/balcony-grills-glass-works-04-card.webp" },
    { src: "/work/balcony-grills-glass-works/balcony-grills-glass-works-05.webp", card: "/work/balcony-grills-glass-works/balcony-grills-glass-works-05-card.webp" },
    { src: "/work/balcony-grills-glass-works/balcony-grills-glass-works-06.webp", card: "/work/balcony-grills-glass-works/balcony-grills-glass-works-06-card.webp" },
    { src: "/work/balcony-grills-glass-works/balcony-grills-glass-works-07.webp", card: "/work/balcony-grills-glass-works/balcony-grills-glass-works-07-card.webp" },
    { src: "/work/balcony-grills-glass-works/balcony-grills-glass-works-08.webp", card: "/work/balcony-grills-glass-works/balcony-grills-glass-works-08-card.webp" },
  ],
  "bathroom-cabinets": [
    { src: "/work/bathroom-cabinets/bathroom-cabinets-01.webp", card: "/work/bathroom-cabinets/bathroom-cabinets-01-card.webp" },
    { src: "/work/bathroom-cabinets/bathroom-cabinets-02.webp", card: "/work/bathroom-cabinets/bathroom-cabinets-02-card.webp" },
  ],
  "curtain-wall": [
    { src: "/work/curtain-wall/curtain-wall-01.webp", card: "/work/curtain-wall/curtain-wall-01-card.webp" },
    { src: "/work/curtain-wall/curtain-wall-02.webp", card: "/work/curtain-wall/curtain-wall-02-card.webp" },
  ],
  "construction-works": [
    { src: "/work/construction-works/construction-works-01.webp", card: "/work/construction-works/construction-works-01-card.webp" },
    { src: "/work/construction-works/construction-works-02.webp", card: "/work/construction-works/construction-works-02-card.webp" },
    { src: "/work/construction-works/construction-works-03.webp", card: "/work/construction-works/construction-works-03-card.webp" },
  ],
  "metal-fabrication": [
    { src: "/work/metal-fabrication/metal-fabrication-01.webp", card: "/work/metal-fabrication/metal-fabrication-01-card.webp" },
  ],
  "signage-fabrication": [
    { src: "/work/signage-fabrication/signage-fabrication-01.webp", card: "/work/signage-fabrication/signage-fabrication-01-card.webp" },
    { src: "/work/signage-fabrication/signage-fabrication-02.webp", card: "/work/signage-fabrication/signage-fabrication-02-card.webp" },
    { src: "/work/signage-fabrication/signage-fabrication-03.webp", card: "/work/signage-fabrication/signage-fabrication-03-card.webp" },
    { src: "/work/signage-fabrication/signage-fabrication-04.webp", card: "/work/signage-fabrication/signage-fabrication-04-card.webp" },
    { src: "/work/signage-fabrication/signage-fabrication-05.webp", card: "/work/signage-fabrication/signage-fabrication-05-card.webp" },
    { src: "/work/signage-fabrication/signage-fabrication-06.webp", card: "/work/signage-fabrication/signage-fabrication-06-card.webp" },
    { src: "/work/signage-fabrication/signage-fabrication-07.webp", card: "/work/signage-fabrication/signage-fabrication-07-card.webp" },
    { src: "/work/signage-fabrication/signage-fabrication-08.webp", card: "/work/signage-fabrication/signage-fabrication-08-card.webp" },
  ],
  "security-doors": [
    { src: "/work/security-doors/security-doors-01.webp", card: "/work/security-doors/security-doors-01-card.webp" },
    { src: "/work/security-doors/security-doors-02.webp", card: "/work/security-doors/security-doors-02-card.webp" },
    { src: "/work/security-doors/security-doors-03.webp", card: "/work/security-doors/security-doors-03-card.webp" },
    { src: "/work/security-doors/security-doors-04.webp", card: "/work/security-doors/security-doors-04-card.webp" },
    { src: "/work/security-doors/security-doors-05.webp", card: "/work/security-doors/security-doors-05-card.webp" },
    { src: "/work/security-doors/security-doors-06.webp", card: "/work/security-doors/security-doors-06-card.webp" },
  ],
  "wall-cladding": [
    { src: "/work/wall-cladding/wall-cladding-01.webp", card: "/work/wall-cladding/wall-cladding-01-card.webp" },
    { src: "/work/wall-cladding/wall-cladding-02.webp", card: "/work/wall-cladding/wall-cladding-02-card.webp" },
    { src: "/work/wall-cladding/wall-cladding-03.webp", card: "/work/wall-cladding/wall-cladding-03-card.webp" },
    { src: "/work/wall-cladding/wall-cladding-04.webp", card: "/work/wall-cladding/wall-cladding-04-card.webp" },
    { src: "/work/wall-cladding/wall-cladding-05.webp", card: "/work/wall-cladding/wall-cladding-05-card.webp" },
    { src: "/work/wall-cladding/wall-cladding-06.webp", card: "/work/wall-cladding/wall-cladding-06-card.webp" },
  ],
};

export type WorkVideo = { src: string; poster: string; card: string };

export const WORK_VIDEOS: Record<string, WorkVideo[]> = {
  "aquariums": [
    { src: "/work/aquariums/aquariums-01.mp4", poster: "/work/aquariums/aquariums-01-poster.webp", card: "/work/aquariums/aquariums-01-card.webp" },
    { src: "/work/aquariums/aquariums-02.mp4", poster: "/work/aquariums/aquariums-02-poster.webp", card: "/work/aquariums/aquariums-02-card.webp" },
    { src: "/work/aquariums/aquariums-03.mp4", poster: "/work/aquariums/aquariums-03-poster.webp", card: "/work/aquariums/aquariums-03-card.webp" },
    { src: "/work/aquariums/aquariums-04.mp4", poster: "/work/aquariums/aquariums-04-poster.webp", card: "/work/aquariums/aquariums-04-card.webp" },
  ],
};

export const workImages = (slug: string): WorkImage[] => WORK_IMAGES[slug] ?? [];
export const heroImage = (slug: string): WorkImage | undefined => WORK_IMAGES[slug]?.[0];
export const workVideos = (slug: string): WorkVideo[] => WORK_VIDEOS[slug] ?? [];
